### ISSUE TITLE
Cover possibility of redirects to other origins within the popin

### ISSUE THREAD

**Issue by krgovind** [explainers-by-googlers/partitioned-popins#4]
In privacycg/storage-partitioning/issues/28, @darkowic mentioned a use-case that involves a redirect/OIDC exchange with another SSO provider within the popin. Is that a scenario we can support with this proposal (assuming that state is still partitioned to the opener)?

**Comment by arichiv** [comment]
redirects within the popin are no issue, but the popin itself remains partitioned regardless of redirect/navigation destination and headers permitting the popin context are required of all pages loaded.

**Comment by krgovind** [comment]
> redirects within the popin are no issue, but the popin itself remains partitioned regardless of redirect/navigation destination and headers permitting the popin context are required of all pages loaded.

That makes sense. Any chance we can document this requirement/behavior in the explainer? I didn't spot it on a quick skim, apologies if it's already there!

**Comment by arichiv** [comment]
It's kind of addressed, but I could add more details:

`
Navigating to or redirecting through a page without a Popin-Policy that permits the opening context to do so will cause the popin to automatically close and report the error to the opening context.
`
