### ISSUE TITLE
Consider moving popinContextType* APIs to window (instead of navigator)

### ISSUE THREAD

**Issue by miketaylr** [explainers-by-googlers/partitioned-popins#7]
🚲 🏠 

I like the advice given in https://github.com/w3ctag/design-principles/issues/448#issuecomment-2219295220.

I think it makes more sense to reason about partitioned window/frame state, not navigator state - and you need to call `window.open` to create one anyways.

**Comment by arichiv** [comment]
@Airborn22 would you be willing to put up a PR with this modification? I can review/approve it

**Comment by sandormajor** [comment]
Sounds good, created https://github.com/explainers-by-googlers/partitioned-popins/pull/8 to update the spec, working on updating the code. Is there a way to attach that PR to this issue?
Edit: I added a comment based on [this](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link the issue but it's not picking it up, I'm also missing the gear icon next to "development" so I might not have the rights to link them.
